import io
import csv
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

def generate_csv_report(tasks):
    """
    Generates a CSV string representation of compliance tasks.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow([
        'Task ID',
        'Checklist Title',
        'Category',
        'Frequency',
        'Cycle Date',
        'Due Date & Time',
        'Current Status',
        'Completed At',
        'Completed By',
        'Inspector Notes',
        'Evidence Attachments Count'
    ])

    for task in tasks:
        completed_by_name = task.completer.full_name if task.completer else 'N/A'
        completed_at_str = task.completed_at.strftime('%Y-%m-%d %H:%M') if task.completed_at else 'N/A'
        due_at_str = task.due_datetime.strftime('%Y-%m-%d %H:%M') if task.due_datetime else 'N/A'
        notes_clean = (task.notes or '').replace('\n', ' ').strip()
        evidence_count = len(task.evidences) if task.evidences else 0

        writer.writerow([
            task.id,
            task.template.title if task.template else 'Unknown',
            task.template.category if task.template else 'General',
            task.template.frequency if task.template else 'DAILY',
            task.cycle_date.strftime('%Y-%m-%d'),
            due_at_str,
            task.effective_status,
            completed_at_str,
            completed_by_name,
            notes_clean,
            evidence_count
        ])

    output.seek(0)
    return output.getvalue()


def generate_pdf_report(tasks, summary_stats, generated_by_name="System Administrator"):
    """
    Builds a professional, print-ready PDF Compliance Audit Report using ReportLab.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E293B'),
        fontName='Helvetica-Bold'
    )
    subtitle_style = ParagraphStyle(
        'DocSub',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B')
    )
    section_heading = ParagraphStyle(
        'SecHead',
        parent=styles['Heading2'],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0F172A'),
        fontName='Helvetica-Bold',
        spaceBefore=10,
        spaceAfter=6
    )
    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#334155')
    )
    cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#0F172A')
    )

    # 1. Header Banner
    story.append(Paragraph("Compliance & Recurring Checklist Tracker", title_style))
    story.append(Paragraph("Official Safety & Regulatory Compliance Audit Report", subtitle_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Generated on: <b>{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</b> | Generated By: <b>{generated_by_name}</b>",
        subtitle_style
    ))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#3B82F6'), spaceAfter=12))

    # 2. Executive KPI Summary Cards Table
    story.append(Paragraph("Executive Compliance Summary", section_heading))
    total = summary_stats.get('total', 0)
    completed = summary_stats.get('completed', 0)
    overdue = summary_stats.get('overdue', 0)
    pending = summary_stats.get('pending', 0)
    rate = summary_stats.get('compliance_rate', 0.0)

    summary_data = [
        [
            Paragraph("<b>Total Tracked Tasks</b>", cell_style),
            Paragraph("<b>Completed</b>", cell_style),
            Paragraph("<b>Overdue / Critical</b>", cell_style),
            Paragraph("<b>Pending</b>", cell_style),
            Paragraph("<b>Compliance Rate</b>", cell_style)
        ],
        [
            Paragraph(f"<font size=13 color='#1E293B'><b>{total}</b></font>", cell_style),
            Paragraph(f"<font size=13 color='#10B981'><b>{completed}</b></font>", cell_style),
            Paragraph(f"<font size=13 color='#EF4444'><b>{overdue}</b></font>", cell_style),
            Paragraph(f"<font size=13 color='#F59E0B'><b>{pending}</b></font>", cell_style),
            Paragraph(f"<font size=13 color='#3B82F6'><b>{rate:.1f}%</b></font>", cell_style)
        ]
    ]

    sum_table = Table(summary_data, colWidths=[108, 108, 108, 108, 108])
    sum_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 14))

    # 3. Tasks Detailed Table
    story.append(Paragraph(f"Detailed Task Inspection Records ({len(tasks)} items)", section_heading))

    table_data = [[
        Paragraph("<b>ID</b>", cell_bold),
        Paragraph("<b>Checklist Title</b>", cell_bold),
        Paragraph("<b>Category</b>", cell_bold),
        Paragraph("<b>Freq</b>", cell_bold),
        Paragraph("<b>Due Date</b>", cell_bold),
        Paragraph("<b>Status</b>", cell_bold),
        Paragraph("<b>Completed By</b>", cell_bold),
        Paragraph("<b>Evidence</b>", cell_bold)
    ]]

    for t in tasks:
        status_color = '#10B981' if t.effective_status == 'COMPLETED' else ('#EF4444' if t.effective_status == 'OVERDUE' else '#F59E0B')
        status_html = f"<font color='{status_color}'><b>{t.effective_status}</b></font>"
        completer_str = t.completer.full_name if t.completer else '-'
        evidence_str = f"{len(t.evidences)} photo(s)" if t.evidences else "None"

        table_data.append([
            Paragraph(str(t.id), cell_style),
            Paragraph(t.template.title[:32] if t.template else 'Unknown', cell_style),
            Paragraph(t.template.category if t.template else 'General', cell_style),
            Paragraph(t.template.frequency[:4] if t.template else 'DLY', cell_style),
            Paragraph(t.due_datetime.strftime('%m/%d %H:%M') if t.due_datetime else '-', cell_style),
            Paragraph(status_html, cell_style),
            Paragraph(completer_str[:15], cell_style),
            Paragraph(evidence_str, cell_style)
        ])

    if len(table_data) == 1:
        table_data.append([Paragraph("No records found matching criteria.", cell_style)] + [Paragraph("", cell_style)] * 7)

    task_table = Table(
        table_data,
        colWidths=[24, 150, 95, 38, 75, 55, 65, 38]
    )
    task_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(task_table)
    story.append(Spacer(1, 24))

    # 4. Sign-off / Verification Block
    story.append(Paragraph("Audit Sign-off & Regulatory Authorization", section_heading))
    sig_data = [
        [
            Paragraph("<b>Inspected & Prepared By:</b>", cell_style),
            Paragraph("<b>Verified By (Safety / Compliance Officer):</b>", cell_style)
        ],
        [
            Paragraph(f"<br/><br/>_______________________________<br/>Signature: {generated_by_name}", cell_style),
            Paragraph("<br/><br/>_______________________________<br/>Signature / Stamp: Lead Auditor", cell_style)
        ]
    ]
    sig_table = Table(sig_data, colWidths=[270, 270])
    sig_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(sig_table)

    # Build the document
    doc.build(story)
    buffer.seek(0)
    return buffer
